import turtle
wn = turtle.Screen()
wn.tracer(2)
print('Screen Made')
def start(turtle):
    turtle.pensize(2)
    turtle.penup()
    turtle.goto(-300,200)
def Rectangle(turtle):
    for i in range(2):
        turtle.pendown()
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(70)
        turtle.right(90)
        turtle.penup()
def drawSuit(turtle,card_value_used):
    turtle.seth(0)
    turtle.pendown()
    if card_value_used == 'Hearts':
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()-5)
        turtle.pendown()
        turtle.left(90)
        turtle.begin_fill()
        turtle.circle(-3.75,180)
        turtle.seth(0)
        turtle.left(90)
        turtle.circle(-3.75,180)
        turtle.right(20)
        turtle.forward(21)
        turtle.right(69*2)
        turtle.forward(21)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(turtle.xcor()+1.24,turtle.ycor()+5.02)
    if card_value_used == 'Diamonds':
        turtle.penup()
        turtle.goto(turtle.xcor()+7.5,turtle.ycor())
        turtle.pendown()
        turtle.begin_fill()
        turtle.right(53.1)
        turtle.forward(12.5)
        turtle.right(36.9*2)
        turtle.forward(12.5)
        turtle.right(53.1*2)
        turtle.forward(12.5)
        turtle.right(36.9*2)
        turtle.forward(12.5)
        turtle.right(53.1)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(turtle.xcor()-7.5,turtle.ycor())
    if card_value_used == 'Clubs':
        turtle.penup()
        turtle.goto(turtle.xcor()+6,turtle.ycor()-20)
        turtle.pendown()
        turtle.begin_fill()
        turtle.forward(2)
        turtle.left(90)
        turtle.forward(5)
        turtle.right(150)
        for i in range(3):
            turtle.circle(4,270)
            turtle.right(165)
        turtle.seth(270)
        turtle.forward(5)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(turtle.xcor()-5.27,turtle.ycor()+20)
    if card_value_used == 'Spades':
        turtle.penup()
        turtle.goto(turtle.xcor()+7.5,turtle.ycor())
        turtle.pendown()
        turtle.begin_fill()
        turtle.right(45)
        turtle.forward(12.5)
        turtle.circle(-5,180)
        turtle.seth(270)
        turtle.left(45)
        turtle.forward(9.22)
        turtle.right(135)
        turtle.forward(14)
        turtle.right(135)
        turtle.forward(9.22)
        turtle.circle(5,-175)
        turtle.seth(60)
        turtle.forward(12.5)
        turtle.right(45)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(turtle.xcor()-1.81,turtle.ycor()-1.66)
    turtle.penup()
def drawValue(turtle,card_value_used):
    turtle.seth(0)
    turtle.pendown()
    if card_value_used == 2:
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor()-10,turtle.ycor()+20)
    elif card_value_used == 3:
        turtle.seth(0)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.backward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+20)
    elif card_value_used == 4:
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.backward(10)
        turtle.forward(20)
        turtle.penup()
        turtle.goto(turtle.xcor()-10,turtle.ycor()+20)
    elif card_value_used == 5:
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+20)
    elif card_value_used == 6:
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+10)
    elif card_value_used == 7:
        turtle.forward(10)
        turtle.right(105)
        turtle.forward(20)
        turtle.penup()
        turtle.goto(turtle.xcor()-4.82,turtle.ycor()+19.32)
    elif card_value_used == 8:
        for i in range(2):
            turtle.forward(10)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor()-10,turtle.ycor()+10)
    elif card_value_used == 9:
        for i in range(5):
            turtle.forward(10)
            turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+20)
    elif card_value_used == 10:
        turtle.pendown()
        turtle.right(90)
        turtle.forward(20)
        turtle.penup()
        turtle.backward(20)
        turtle.left(90)
        turtle.forward(5)
        turtle.pendown()
        for i in range(2):
            turtle.forward(5)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.penup()
        turtle.goto(turtle.xcor()-5,turtle.ycor())
    elif card_value_used == 'J':
        turtle.forward(10)
        turtle.backward(4)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(6)
        turtle.right(90)
        turtle.forward(4)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+16)
    elif card_value_used == 'Q':
        for i in range(2):
            turtle.forward(10)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.right(60)
        turtle.penup()
        turtle.forward(15)
        turtle.left(10)
        turtle.pendown()
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor()-13.93,turtle.ycor()+20.65)
    elif card_value_used == 'K':
        turtle.right(90)
        turtle.forward(20)
        turtle.backward(10)
        turtle.left(140)
        turtle.forward(13)
        turtle.backward(13)
        turtle.right(100)
        turtle.forward(15)
        turtle.penup()
        turtle.goto(turtle.xcor()-9.64,turtle.ycor()+21.49)
    elif card_value_used == 'A':
        turtle.penup()
        turtle.forward(6)
        turtle.pendown()
        turtle.right(72)
        turtle.forward(22)
        turtle.backward(22)
        turtle.right(35)
        turtle.forward(22)
        turtle.backward(11)
        turtle.left(107)
        turtle.forward(7)
        turtle.penup()
        turtle.goto(turtle.xcor()-12.79,turtle.ycor()+10.52)
    turtle.penup()
def drawingCard(turtle,card_value_used):
    turtle.color('black')
    turtle.setheading(0)
    Rectangle(turtle)
    if card_value_used[1] == 'Hearts' or card_value_used[1] == 'Diamonds':
        turtle.color('red')
    else:
        turtle.color('black')
    turtle.goto(turtle.xcor()+5,turtle.ycor()-5)
    drawValue(turtle,card_value_used[0])
    turtle.goto(turtle.xcor()+10,turtle.ycor()-20)
    drawSuit(turtle,card_value_used[1])
    turtle.goto(turtle.xcor()+17,turtle.ycor()-15)
    drawValue(turtle,card_value_used[0])
    turtle.goto(turtle.xcor()+35,turtle.ycor()+40)
# wn.exitonclick()
