import turtle
wn = turtle.Screen()
wn.tracer(2,10)
def start(turtle):
    turtle.pensize(2)
    turtle.penup()
    turtle.goto(-300,200)
def Rectangle(turtle):
    for i in range(2):
        turtle.pendown()
        turtle.forward(45)
        turtle.right(90)
        turtle.forward(70)
        turtle.right(90)
        turtle.penup()
def drawValue(turtle,card_value_used):
    turtle.seth(0)
    turtle.pendown()
    if card_value_used == 2:
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor()-10,turtle.ycor()+20)
    elif card_value_used == 3:
        turtle.seth(0)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.backward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+20)
    elif card_value_used == 4:
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.backward(10)
        turtle.forward(20)
        turtle.penup()
        turtle.goto(turtle.xcor()-10,turtle.ycor()+20)
    elif card_value_used == 5:
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+20)
    elif card_value_used == 6:
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+10)
    elif card_value_used == 7:
        turtle.forward(10)
        turtle.right(105)
        turtle.forward(20)
        turtle.penup()
        turtle.goto(turtle.xcor()-4.82,turtle.ycor()+19.32)
    elif card_value_used == 8:
        for i in range(2):
            turtle.forward(10)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor()-10,turtle.ycor()+10)
    elif card_value_used == 9:
        for i in range(5):
            turtle.forward(10)
            turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+20)
    elif card_value_used == 10:
        turtle.pendown()
        turtle.right(90)
        turtle.forward(20)
        turtle.penup()
        turtle.backward(20)
        turtle.left(90)
        turtle.forward(5)
        turtle.pendown()
        for i in range(2):
            turtle.forward(5)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.penup()
        turtle.goto(turtle.xcor()-5,turtle.ycor())
    elif card_value_used == 'J':
        turtle.forward(10)
        turtle.backward(4)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(6)
        turtle.right(90)
        turtle.forward(4)
        turtle.penup()
        turtle.goto(turtle.xcor(),turtle.ycor()+16)
    elif card_value_used == 'Q':
        for i in range(2):
            turtle.forward(10)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.right(60)
        turtle.penup()
        turtle.forward(15)
        turtle.left(10)
        turtle.pendown()
        turtle.forward(10)
        turtle.penup()
        turtle.goto(turtle.xcor()-13.93,turtle.ycor()+20.65)
    elif card_value_used == 'K':
        turtle.right(90)
        turtle.forward(20)
        turtle.backward(10)
        turtle.left(140)
        turtle.forward(13)
        turtle.backward(13)
        turtle.right(100)
        turtle.forward(15)
        turtle.penup()
        turtle.goto(turtle.xcor()-9.64,turtle.ycor()+21.49)
    elif card_value_used == 'A':
        turtle.penup()
        turtle.forward(6)
        turtle.pendown()
        turtle.right(72)
        turtle.forward(22)
        turtle.backward(22)
        turtle.right(35)
        turtle.forward(22)
        turtle.backward(11)
        turtle.left(107)
        turtle.forward(7)
        turtle.penup()
        turtle.goto(turtle.xcor()-12.79,turtle.ycor()+10.52)
    turtle.penup()
def drawingCard(turtle,card_value_used):
    turtle.setheading(0)
    Rectangle(turtle)
    turtle.goto(turtle.xcor()+5,turtle.ycor()-5)
    drawValue(turtle,card_value_used[0])
    turtle.goto(turtle.xcor()+25,turtle.ycor()-40)
    drawValue(turtle,card_value_used[0])
    turtle.goto(turtle.xcor()+30,turtle.ycor()+45)
