import turtle
wn = turtle.Screen()
# wn.tracer(2)
hand = [[10,'Hearts'],['A','Clubs']]
card = turtle.Turtle()
card.penup()
card.goto(-300,200)
for i in hand:
    print(i)
def Rectangle(turtle):
    for i in range(2):
        turtle.forward(45)
        turtle.right(90)
        turtle.forward(70)
        turtle.right(90)
def drawValue(turtle,value):
    if value[0] == 10:
        turtle.pendown()
        turtle.right(90)
        turtle.forward(20)
        turtle.penup()
        turtle.backward(20)
        turtle.left(90)
        turtle.forward(5)
        turtle.pendown()
        for i in range(2):
            turtle.forward(10)
            turtle.right(90)
            turtle.forward(20)
            turtle.right(90)
        turtle.penup()
    elif value[0] == 'J':
        turtle.forward(20)
        turtle.backward(10)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
    elif value[0] == 'A':
        turtle.penup()
        turtle.forward(8)
        turtle.pendown()
        turtle.right(72)
        turtle.forward(22)
        turtle.backward(22)
        turtle.right(35)
        turtle.forward(22)
        turtle.backward(11)
        turtle.left(107)
        turtle.forward(8)
def drawingCard(turtle):
    card.penup()
    turtle.goto(-300,200)
    card.pendown()
    Rectangle(turtle)
    card.penup()
    turtle.goto(-295,195)
    drawValue(turtle,hand[0])
    turtle.goto(-275,155)
    drawValue(turtle,hand[0])
    turtle.penup()
    turtle.goto(-250, 200)
    card.pendown()
    Rectangle(turtle)
    card.penup()
    turtle.goto(-245,195)
    card.pendown()
    drawValue(turtle,hand[1])
    card.penup()
    turtle.goto(-225,155)
    card.setheading(0)
    card.pendown()
    drawValue(turtle,hand[1])

drawingCard(card)
wn.exitonclick()
